[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gnumake", "gcc"]

[phases.install]
cmds = [
  "yarn --cwd backend install",
  "yarn --cwd backend run rebuild-sqlite",
  "yarn --cwd frontend install"
]

[phases.build]
cmds = ["yarn --cwd frontend build"]

[start]
cmd = "FRONTEND_DIST=frontend/dist/frontend/browser node backend/src/app.js"
