[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && yarn install --frozen-lockfile",
  "cd frontend && yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["cd frontend && yarn build"]

[start]
cmd = "FRONTEND_DIST=/app/frontend/dist/frontend/browser node /app/backend/src/app.js"
